// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7kI8VPhsNHlJl4YtEc_awi4JkYFH2Kxk',
    appId: '1:1031304974777:web:4468a8e2dd3b0ec37be668',
    messagingSenderId: '1031304974777',
    projectId: 'minimart-a8d32',
    authDomain: 'minimart-a8d32.firebaseapp.com',
    storageBucket: 'minimart-a8d32.appspot.com',
    measurementId: 'G-JBWPEW47RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0JYp58T8uiYmP_ubwdKYSp7l2XcWfthk',
    appId: '1:1031304974777:android:6beb01e339a080c27be668',
    messagingSenderId: '1031304974777',
    projectId: 'minimart-a8d32',
    storageBucket: 'minimart-a8d32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRCVBl55gJQKuE4Y_3n57N5mfyqOFh3vs',
    appId: '1:1031304974777:ios:df5fd67b3f1b1bfd7be668',
    messagingSenderId: '1031304974777',
    projectId: 'minimart-a8d32',
    storageBucket: 'minimart-a8d32.appspot.com',
    iosClientId: '1031304974777-4shmdt1bka1ume4io2f0utn9hka7aqaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.minimart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRCVBl55gJQKuE4Y_3n57N5mfyqOFh3vs',
    appId: '1:1031304974777:ios:df5fd67b3f1b1bfd7be668',
    messagingSenderId: '1031304974777',
    projectId: 'minimart-a8d32',
    storageBucket: 'minimart-a8d32.appspot.com',
    iosClientId: '1031304974777-4shmdt1bka1ume4io2f0utn9hka7aqaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.minimart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7kI8VPhsNHlJl4YtEc_awi4JkYFH2Kxk',
    appId: '1:1031304974777:web:c7bc50ca439421a77be668',
    messagingSenderId: '1031304974777',
    projectId: 'minimart-a8d32',
    authDomain: 'minimart-a8d32.firebaseapp.com',
    storageBucket: 'minimart-a8d32.appspot.com',
    measurementId: 'G-8XEPWQMD0B',
  );
}
